# Generated by Django 4.2.1 on 2023-05-16 21:22

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lendable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='LendableStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Status of Lendable')),
            ],
        ),
        migrations.CreateModel(
            name='LendableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Type of Lendable')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Address name')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=1024, verbose_name='City or Town')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('postal_code', models.CharField(max_length=12, verbose_name='Zip or Postal Code')),
                ('country', models.CharField(max_length=2, verbose_name='Country')),
                ('point_geometry', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326, verbose_name='Address Point')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lending_library.location')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('confirmed_by_lender', models.BooleanField(default=False)),
                ('confirmed_by_borrower', models.BooleanField(default=False)),
                ('borrowing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lendable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lending_library.lendable')),
            ],
        ),
        migrations.AddField(
            model_name='lendable',
            name='lendable_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lending_library.lendablestatus'),
        ),
        migrations.AddField(
            model_name='lendable',
            name='lendable_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lending_library.lendabletype'),
        ),
        migrations.AddField(
            model_name='lendable',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
