services:

  sveltekit:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - "3000:3000"
  db:
    image: postgis/postgis
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped

  django:
    build: 
      context: .
      dockerfile: ./config/backend/Dockerfile-local
    command: ./config/backend/start-local.sh
    volumes:
      - .:/code
      - static:/static
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    restart: unless-stopped

  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile-local
    volumes:
      - certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /etc/acme.sh
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - static:/static
    ports:
      - '80:80'
      - '443:443'
    restart: always


volumes:
   certs:
   db:
   static: