# Generated by Django 4.2.1 on 2023-06-01 14:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending_library', '0002_alter_lendablestatus_options_lendable_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=1024, verbose_name='City or Town'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='point_geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326, verbose_name='Location Point'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='State'),
        ),
    ]
