# Generated by Django 4.2.1 on 2023-08-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending_library', '0004_network_owner_alter_location_point_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
