import { Inter } from "next/font/google";
import "src/styles/globals.css";
import Navigation from "src/components/Navigation";
import { getToken } from "./auth/actions";

const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={inter.variable}>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
