# syntax=docker/dockerfile:1
FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
#COPY requirements.txt /code/
#RUN pip install -r requirements.txt
RUN pip install pipenv
COPY ./Pipfile ./Pipfile.lock /code/
RUN pipenv install --system --deploy && apt-get update && apt-get upgrade -y && apt-get install -y binutils libproj-dev gdal-bin postgis
COPY ./backend .
# .env can be generated with initialize_dotenv.py
COPY ./.env ./.env
COPY ./config/backend/start-local.sh .
RUN chmod +x /code/start-local.sh
